#!/bin/bash
#--Jira Node Failure Root Cause Analyzer. Scans jira + catalina logs for fatal patterns
#--Basanite by Valeri Tikhonov, TD, April 2026.
##--https://confluence.atlassian.com/jirakb/useful-log-files-in-jira-data-center-1027120387.html
#--The log files with a star "*" in the end indicate that the logs roll over. For example, the latest file is atlassian-jira.log, then atlassian-jira.log.1, then atlassian-jira.log.2 and so on.
#JIRA_INSTALL/logs
	#access_log.YYYY-mm-dd --HTTP access log (Tomcat), A list of each request that Jira node completed processing. Logged by the Tomcat application server
	#catalina.out, catalina.YYYY-mm-dd.log --Tomcat application server process stdout. This file isn't managed by Jira's logging solution log4j, so the format of entries here varies. OutOfMemoryError is logged here.
	#atlassian-jira-gc-YYYY-mm-dd_hh-mm-ss.log.* --Garbage collection log, by JVM, Java heap memory management, and what memory is in use. Out of memory errors or memory contention problems.
#JIRA_HOME/log
	#atlassian-jira.log* --Primary Jira log file, Generic log location, including logs that aren’t specifically directed elsewhere
	#atlassian-jira-perf.log* --Performance statistics. A variety of useful performance metrics about the application and underlying system, for example, database latency, tomcat thread pool utilisation, system/process CPU consumption, and DBCP (database connection) pool utilisation
	#atlassian-jira-app-monitoring.log* --App performance stats. Instrumentation of first and third party app performance such as the count and time spent on database operations, issue/comment indexing, and cache removals
	#atlassian-jira-slow-queries.log* --Slow JQL log. Records JQL query and their source for executions over the threshold of 400ms
	#atlassian-jira-querydsl-sql.log* --QueryDSL debug log. QueryDSL debug log, a SQL abstraction layer used by some Jira functions/plugins
	#atlassian-jira-slow-querydsl-queries.log* --Slow QueryDSL log. A record of slowly performing QueryDSL SQL queries
	#atlassian-jira-sql.log* --SQL Debug Log. A list of SQL queries sent by the application's (Apache) ofbiz library when SQL debug logging is enabled
	#atlassian-jira-ipd-monitoring.log* --In-product-diagnostics. Additional performance metrics generated by the "In product diagnostics" plugin
	#jira-diagnostics.log --Diagnostic Alerts. A variety of useful performance statistics, usually logged when a certain theshold is reached. For instance, slowly performing HTTP requests, high scheduler thread pool utilisation, and so on
	#atlassian-jira-stats.log* --Jira Stats. Metrics used to troubleshoot performance problems
	#atlassian-greenhopper.log --Jira Software Agile Board log. Logging written by the Jira Software plugin
	#atlassian-servicedesk.log* --Jira Service Management log. Logging written by the Jira Service Management plugin
	#atlassian-jira-security.log* --Security Log. Records login success/failure transactions, session creation and destruction, along with certain authentication related debug logging if enabled
	#atlassian-jira-apdex.log* --Apdex log. Apdex performance statistics
	#atlassian-jira-http-access.log* --HTTP access log (Jira). A HTTP access log implemented by Jira itself when HTTP access log debug is enabled. Tomcat's access log is typically recommended over this log, since it is always enabled, has lower performance overhead, and provides almost all information that this access log provides. Due to the risk to performance, we don't recommend enabling Jira's access log in enterprise scale production instances except in certain edge cases
	#atlassian-jira-http-dump.log* --HTTP dump log (Jira). An extremely verbose HTTP dump log, written by Jira. Only written if HTTP dump logging is enabled. Due to the risk to performance, we don't recommend enabling Jira's access log in enterprise scale production instances. 
	#atlassian-jira-incoming-mail.log* --Incoming mail. Incoming mail debug log. Only written to if Incoming Mail Debug is enabled
	#atlassian-jira-outgoing-mail.log* --Outgoing mail. Outgoing mail debug log. Only written to if Outgoing Mail Debug is enabled
#JIRA_HOME/log/audit
	#YYYYmmdd.00000.audit.log --Audit logging. Filesystem historical logging of audit data
#JIRA_HOME/log/jfr
	#atst_in_product_diagnostic_YYYY_MM_DD_HH_mm_ss.jfr --Java Flight Recorder. A low level capture of performance statistics from the JVM - rolling N minutes for N bytes
	#atst_in_product_diagnostic_dump_on_exit_YYYY_MM_DD_HH_mm_ss.jfr --Java Flight Recorder. A low level capture of performance statistics from the JVM (auto-generated on exit)
#JIRA_INSTALL/.install4j
	#installation.log --Jira installer logs. Records all the steps performed by the Jira Installer binary. Not applicable when Jira is installed manually via tgz file or container

CONF_INSTALL="${1:-/media/user/Storage/@jira_logs_copy/jira_sys/logs/}"
CONF_HOME="${2:-/media/user/Storage/@jira_logs_copy/logsamples/home_logs/}"
CONF_HOME_AUDIT="${JIRA_HOME}audit/"
CONF_HOME_JFR="${JIRA_HOME}jfr/"

JIRA_INSTALL="${1:-/media/user/Storage/@jira_logs_copy/jira_sys/logs/}"
JIRA_HOME="${2:-/media/user/Storage/@jira_logs_copy/logsamples/home_logs/}"
JIRA_HOME_AUDIT="${JIRA_HOME}audit/"
JIRA_HOME_JFR="${JIRA_HOME}jfr/"
#--Logs
#JIRA_LOG=${1:-/home/user/atlassian-jira-home/log/atlassian-jira.log}
#CATALINA_LOG=${2:-/home/user/atlassian-jira-software/logs/catalina.out}
CATALINA_LOG="${JIRA_INSTALL}catalina.out"
JIRA_LOG="${JIRA_HOME}atlassian-jira.log"
JIRA_SLOW_JQL="${JIRA_HOME}atlassian-jira-slow-queries.log"
# ./media/user/Storage/lenovo-storage/@Mobile/@Wiki/Projects/@Java/@Jira/temp_collection_of_scripts_to_be_sorted/bash/basaniteLogs.sh #--RUN
REPORTS="/media/user/Storage/lenovo-storage/@Mobile/@Wiki/Projects/@Java/@Jira/temp_collection_of_scripts_to_be_sorted/bash/tmp/basanite_FailureRCAnalysis_$(date +%Y%m%d-%H%M%S)"
mkdir -p $REPORTS
#sudo su - user
#jiraLogName=$(basename "$JIRA_LOG")
#catalinaLogName=$(basename "$CATALINA_LOG")
jiraLogName="${JIRA_LOG##*/}"
jiraSlowJql="${JIRA_SLOW_JQL##*/}"
catalinaLogName="${CATALINA_LOG##*/}"

#--Use Linear Array example:
#keywordsArr=("word1" "word2")
#keywordsArr+=("word3")
#1. for keyword in ${keywordsArr[@]}
#2. for i in ${!keywordsArr[@]}
#3. length=${#keywordsArr[@]}
#3. for ((i=0; i<length; i++)); do
#	echo -e "\n~~$i. ${keywordsArr[$i]}~~" >> $BasaniteRCAReportLog #--SubHeader/Filter
#	grep -E ${keywordsArr[$i]} $JIRA_LOG >> $BasaniteRCAReportLog #--Log extract
#done

#2026-04-23 15:34:53,722-0400
#2026-04-23 15:35:07,600-0400 
DateRange="^2026-04-23[[:space:]]15:3[45]"
DateRange="^2026-04-[0-3]"
BasaniteRCAReportLog="$REPORTS/BasaniteRCAReport.log"

declare -A keywordsMap
#keywordsMap=(["Atlassian-errors"]="[[:space:]]+(ERROR|FATAL|SEVERE|CRITICAL)[[:space:]]+" ["Exceptions"]="[A-Za-z0-9\.]+Exception")
keywordsMap["${jiraLogName}, Atlassian-errors"]="[[:space:]]+(ERROR|FATAL|SEVERE|CRITICAL)[[:space:]]+"
keywordsMap["${jiraLogName}, Exceptions"]="[A-Za-z0-9\.]+Exception"
keywordsMap["${jiraSlowJql}, Slow JQL"]="took[[:space:]][0-9]+[[:space:]]ms|Slow[[:space:]]request"
keywordsMap["${jiraLogName}, SlowRESTRequests"]="Request.*took|Slow[[:space:]]request" # Detect request timeout / slow endpoints
keywordsMap["Cluster-health"]="Cluster.*lost|node.*not[[:space:]]responding|heartbeat|split[[:space:]]brain"
keywordsMap["JvmOutOfMemory"]="OutOfMemoryError" #JVM memory failures
keywordsMap["DatabaseFailures"]="connection.*fail|database.*down|PSQLException|SQLTransientConnectionException"
keywordsMap["PluginFailures"]="Plugin.*failed|Unable[[:space:]]to[[:space:]]start[[:space:]]plugin|OSGi|Spring[[:space:]]context[[:space:]]failed"
keywordsMap["ThreadPoolStarvation"]="Thread.*blocked|StuckThread|thread[[:space:]]starvation"
keywordsMap["StuckRequestThreads"]="StuckThread"
keywordsMap["NodeShutdownTrigger"]="Shutdown|Stopping[[:space:]]Jira|Jira[[:space:]]is[[:space:]]shutting[[:space:]]down"

declare -A keywordsMapPiped
#keywordsMapPiped[""]=""

for keyword in "${!keywordsMap[@]}"; do
	echo -e "\n~~cat: $keyword: ${keywordsMap[$keyword]}" >> $BasaniteRCAReportLog #--SubHeader/Filter
	grep -E $DateRange $JIRA_LOG | grep -hE ${keywordsMap[$keyword]} >> $BasaniteRCAReportLog
	echo -e "\n~~cat: $keyword: ${keywordsMap[$keyword]}" >> $BasaniteRCAReportLog #--SubHeader/Filter
	grep -E $DateRange $CATALINA_LOG | grep -hE ${keywordsMap[$keyword]} >> $BasaniteRCAReportLog
done

##--Detect thread explosion, thread growth
echo -e "\n~~cat: ThreadExplosion" >> $BasaniteRCAReportLog
grep -E $DateRange $CATALINA_LOG | grep -E "http-nio|http-bio|ThreadPoolExecutor" | grep -E "max[[:space:]]threads|busy[[:space:]]threads|stuck[[:space:]]thread" >> $BasaniteRCAReportLog


echo -e "\n~~cat: LoadBalancerHealthCheck" >> $BasaniteRCAReportLog
grep -E "healthcheck|status|heartbeat" $JIRA_LOG | grep -E "fail|timeout|unreachable" >> $BasaniteRCAReportLog


##--Top exceptions summary
grep -E $DateRange $JIRA_LOG | grep -oE "[A-Za-z0-9\.]+Exception" | sort | uniq -c | sort -nr | head -10 >> $REPORTS/BasaniteRCAtopExceptions.log


#--The "Quick Peak"
#--1. extracts the date and time (down to the minute), 
#--2. counts errors per minute, and sorts them so the highest density appears at the top:
#--cut -c 1-16: Clips the first 16 characters of the line (2026-04-29 21:51), this captures the Year-Month-Day Hour:Minute.
#--uniq -c: Groups identical minutes together and counts how many times they appear. Only works if your log file is already in chronological order.
#--sort -n: Sorts the results numerically by the count. The "sharpest" density increase will be at the very bottom of the list.
#grep -E $DateRange $JIRA_LOG | grep -E "[[:space:]]ERROR[[:space:]]" | cut -c 1-16 | uniq -c | sort -nr >> $REPORTS/BasaniteRCAMostErrorsPerMinute.log
#--If you want to see the timeline in order but highlight where the jumps happen:
grep -E $DateRange $JIRA_LOG | grep -E "[[:space:]]ERROR[[:space:]]|Exception" | cut -c 1-16 | uniq -c >> $REPORTS/BasaniteRCASpikesList.log
#--Visualizing with a "Text Bar Chart"
grep -E $DateRange $JIRA_LOG | grep -E "[[:space:]]ERROR[[:space:]]|Exception" | cut -d' ' -f2 | cut -d':' -f1,2 | sort | uniq -c | awk '{printf "%s %s ", $2, $1; for(i=0; i<$1/10; i++) printf "#"; print ""}' >> $REPORTS/BasaniteRCASpikesChart.log



##--echo "Last 50 ERROR timeline:"
tail -50 $JIRA_LOG > $REPORTS/BasaniteRCAJiraLogTail.txt
echo "Failure Root Cause Analysys completed. Reports saved to: $REPORTS"
